#
# avendesora: malkier irc server
# etc/config.yml: configuration information
#
# Copyright (c) 2003-2009 Eric Will <rakaur@malkier.net>
#
# encoding: utf-8

# This file is written in YAML. I decided to go with it over the
# complex C-style configuration in synapse for a few reasons:
#
#   1) It's very simple.
#   2) Ruby can parse it with one method call rather than an entire library.
#   3) It's very Ruby-ish instead of C-ish, and that's what I'm going for.
#

##
# How much logging should we do?
# In order of least verbose to most verbose:
# none, fatal, error, warning, info, debug
logging: info

# This is to make sure you read your config. Comment out.
#die: true

